version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
  cloudrun: circleci/gcp-cloud-run@1.0.0
  slack: circleci/slack@4.5.0
  
workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
     - build_and_deploy_job:
        filters:
          branches:
            only:
              - main

jobs:
  build_and_deploy_job:
    docker:
      - image:  google/cloud-sdk:latest
    steps:
      - checkout
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "Congrats!!!",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      
      - run:
          name: login GCP
          command: |
            echo $GCLOUD_SERVICE_KEY > /tmp/key.json 
            gcloud auth activate-service-account --key-file=/tmp/key.json 
            rm /tmp/key.json 
            gcloud  config set project $GOOGLE_PROJECT_ID	
            gcloud config set compute/region $GOOGLE_COMPUTE_REGION
            gcloud config set compute/zone $GOOGLE_COMPUTE_ZONE
           
            gcloud beta run deploy  --image=$IMAGE_NAME	 --platform=managed --region=$GOOGLE_COMPUTE_REGION --allow-unauthenticated
